# Generated by Django 3.2.7 on 2021-09-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='projects/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': ' Projects',
            },
        ),
    ]
