# Generated by Django 3.2.7 on 2021-09-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cms',
            options={'verbose_name': 'CMS', 'verbose_name_plural': 'CMS'},
        ),
    ]
