# Generated by Django 3.2.7 on 2021-10-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newletter', '0003_alter_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
