# Generated by Django 3.2.7 on 2021-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': ' Tutorials',
                'verbose_name_plural': ' Tutorials',
            },
        ),
    ]
